GRID_SIZE = 16
CANVAS_WIDTH = GRID_SIZE * 20
CANVAS_HEIGHT = GRID_SIZE * 16
CANVAS_SCALE = 3

DEBUG = false
DEBUG_PLAYER = DEBUG or true
DEBUG_ENEMIES = DEBUG or false
DEBUG_WORLD = DEBUG or false
DEBUG_GAME_OBJECTS = DEBUG or false
